### ISSUE TITLE
How to use setAcceptBlock and setCancelBlock DZNPhotoEditorViewController in swift

### ISSUE THREAD

**Issue by ppsdang** [dzenbot/DZNPhotoPickerController#91]
I am not getting the idea how to use setAcceptBlock and setCancelBlock in swift while using  DZNPhotoEditorViewController

var editor:DZNPhotoEditorViewController = DZNPhotoEditorViewController(image: image)
        editor.cropMode = DZNPhotoEditorViewControllerCropMode.Square
        editor.cropSize = CGSizeMake(CGRectGetWidth(self.view.frame), 200.0)
        selectedImageIndexForEditing = index
self.navigationController?.pushViewController(editor, animated: true)

**Comment by ppsdang** [comment]
I am unable to get the methods setAcceptBlock and setCancelBlock like editor.setAcceptBlock.
Please suggest a wayout.

**Comment by Melmer** [comment]
In Swift you have to use closures for blocks


If you've got still the problem. You can fix it like this:

```swift
editor.acceptBlock = { (editor:DZNPhotoEditorViewController!, userInfo: [ NSObject: AnyObject]!) in
//handling here
}
```
           
```swift
editor.cancelBlock = { (editor:DZNPhotoEditorViewController!) in
//handling here
}
```
